version: "3.8"

services:
  # Conteneur MySQL
  db:
    image: mysql:8.0
    container_name: docker_mysql
    restart: always
    volumes: 
      - db-data:/var/lib/mysql
    environment: 
      MYSQL_ROOT_PASSWORD: symfony
      MYSQL_DATABASE: abdelhakmireda
      MYSQL_USER: symfony
      MYSQL_PASSWORD: symfony
    networks: 
      - dev

  # Conteneur phpMyAdmin
  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin
    container_name: docker_phpmyadmin
    restart: always
    environment:
      PMA_HOST: db
    ports:
      - "8080:80"
    networks:
      - dev

  # Conteneur Apache + PHP 8.1
  www:
    build: ./php
    container_name: docker_www
    ports:
      - "8082:80"
    volumes: 
      - ./php/vhosts:/etc/apache2/sites-enabled
      - ./:/var/www
    restart: always
    networks: 
      - dev

networks: 
  dev:

volumes: 
  db-data: